### ISSUE TITLE
Uncaught TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by codefrenzy** [dataarts/webgl-globe#28]
Hi there,

I'm trying to render 8 different series, each with a different number of points in it (between 2 and 5 points, so really small amount of data).

This seems to cause the following error in the three.min.js library - Uncaught TypeError: Cannot read property 'x' of undefined. If I include less data (so 2 less points in the first series), this error is not thrown and the globe renders correctly. It's almost as though if the first series has more points in it than other series, it causes this error. 

Does this mean that all series need to have the same number of points in them? Or that the first series should be the series with the most points? It seems that would be really limiting if that were the case. I hope it's not!

I'd really appreciate some help if at all possible :)

Cheers,
Annie

**Comment by mrdoob** [comment]
Unfortunately this section is for bug reports and feature requests.
For help request I would recommend using [StackOverflow](http://stackoverflow.com/) instead.

**Comment by codefrenzy** [comment]
Hi mrdoob,

I understand - but I actually think this is a bug. It sounds very much along the same lines as https://github.com/dataarts/webgl-globe/issues/13 (see the last comment). 

I think this is a bug with your three.js library because it works perfectly with other almost identical datasets. The error is thrown in your library, not my code. I'm happy to post a question on StackOverflow but I don't know how anyone who is using your libraries is going to know how to fix it if the problem is internal?

Cheers,
Annie

**Comment by codefrenzy** [comment]
Hi again,

I've gotten a bit further in debugging this issue. I downloaded the un-minified version of three.js and can see the error is happening on line 19468:

```javascript
vka[ offset_morphTarget ]     = v1.x;
```

If I add the following if statement around all the lines that refer to v1, v2 and v3:

```javascript
if (typeof(v1) != 'undefined' && typeof(v2) != 'undefined' && typeof(v3) != 'undefined')
```

So in other words:

```javascript
if (typeof(v1) != 'undefined' && typeof(v2) != 'undefined' && typeof(v3) != 'undefined')
{					
	vka[ offset_morphTarget ]     = v1.x;
	vka[ offset_morphTarget + 1 ] = v1.y;
	vka[ offset_morphTarget + 2 ] = v1.z;

	vka[ offset_morphTarget + 3 ] = v2.x;
	vka[ offset_morphTarget + 4 ] = v2.y;
	vka[ offset_morphTarget + 5 ] = v2.z;

	vka[ offset_morphTarget + 6 ] = v3.x;
	vka[ offset_morphTarget + 7 ] = v3.y;
	vka[ offset_morphTarget + 8 ] = v3.z;					
}
```

Then the globe renders without throwing any errors, although I think the points are no longer drawn in the correct place.

Would you consider this to be a bug?

Cheers,
Annie

**Comment by mrdoob** [comment]
It sounds like it's a problem in the dataset itself. At the moment, this project doesn't double check that the data being passed is correct.

**Comment by codefrenzy** [comment]
Hi @mrdoob, 

I can't see what would be wrong with the dataset. Like I said, I have 8 series, all of which have between 2~5 data points in them. This works fine if the first series only has 2 data points - which could be because all other series have *at least* 2 data points in them too. As soon as I add a third data point to the first series, it breaks. Hence my suspicion that the number of data points in each series either has to be equal or at the very least, have as many as the series before them.

Can you confirm if there is such a limitation? I'm happy to send you some data if it would help debug this.

**Comment by mrdoob** [comment]
Yes. All the data sets have to have equal amount of data points.

**Comment by codefrenzy** [comment]
Well that answers the question then. Can I put a feature request in to allow data sets with differing numbers of data points? :)

**Comment by mrdoob** [comment]
You can. But the project is a bit stale...

**Comment by mattslocum** [comment]
Can you explain the reason for the problem a little more? I'm having the same problem. Do I need to 
this.points = new THREE.Mesh(....)
every time I call createPoints() on data that doesn't have the same points?
Any help from a threeJS expert?
