### ISSUE TITLE
Uncaught network error - Running on chrome

### ISSUE THREAD

**Issue by ezequias** [dataarts/webgl-globe#35]
Hello everybody

I am having trouble to see index.html after a checkout. Please check this error out.

See picture below:

![globeerror](https://cloud.githubusercontent.com/assets/539561/9552628/fc9a3fe2-4d8f-11e5-87dd-a2b6e4849c98.jpg)

Thanks in advance.

**Comment by mrdoob** [comment]
You need to setup a local webserver first (or run chrome with the `--allow-file-access-from-files` flag)

**Comment by ezequias** [comment]
I tried the flag but it does not work for me. Thank you for the advice anyway @mrdoob
