### ISSUE TITLE
Why create morphPadding elements inside morphTargets???

### ISSUE THREAD

**Issue by Javingka** [dataarts/webgl-globe#57]
Hello,

I have this doubt,
Why is necessary include this padding to the morphTargets array? and less than 8?

````
        if (this._baseGeometry.morphTargets.length < 8) {
          console.log('t l',this._baseGeometry.morphTargets.length);
          var padding = 8-this._baseGeometry.morphTargets.length;
          console.log('padding', padding);
          for(var i=0; i<=padding; i++) {
            console.log('padding',i);
            this._baseGeometry.morphTargets.push({'name': 'morphPadding'+i, vertices: this._baseGeometry.vertices});
          }
        }
````
(snippet from   function createPoints()...  within Globe.js)

if latter in the this.\__defineSetter__ function we do this, using only the MorphTarget: 

````
    var morphDict = this.points.morphTargetDictionary;
    for(var k in morphDict) {
      if(k.indexOf('morphPadding') < 0) {
        validMorphs.push(morphDict[k]);
      }
    }
````
(snippet from this.\__defineSetter__('time', function(t)... within Globe.js)

So. 
<b>when are the morphPadding useful? </b>

Thanks so much for your help, I am trying to understand all the code

**Comment by mrdoob** [comment]
`three.js` currently need `morphTargets` to be `8`.
