### ISSUE TITLE
Cannot run any Globes locally

### ISSUE THREAD

**Issue by 3dmund** [dataarts/webgl-globe#61]
When I open index.html in the folder globe, there is no globe. This is what it looks like, and I get the error messages logged to console in the bottom right.

<img width="1280" alt="screen shot 2016-10-27 at 11 10 42 pm" src="https://cloud.githubusercontent.com/assets/13290044/19796631/a9d17522-9c9a-11e6-9ccd-ba988bab70fa.png">

**Comment by 3dmund** [comment]
I fixed the last error and now I just get this error. If someone can help that would be greatly appreciated. This is for a coding challenge due this weekend. Thanks!

<img width="1280" alt="screen shot 2016-10-27 at 11 13 49 pm" src="https://cloud.githubusercontent.com/assets/13290044/19796707/15956da4-9c9b-11e6-91b9-e6dd1a0d3c7e.png">

**Comment by guillaumeguerin** [comment]
You can't double clic on your index.html and expect it to workd.

You need to run a server first, put your files in it, and access it via something like localhost:8080/globe/index.html, then it will work.
Have a look at XAMPP for example.

**Comment by brtknr** [comment]
If you have python installed, change to the root folder containing this repository, then run the following on terminal/command.exe:
$ python -m http.server 8080

Then on your browser, type:
http://localhost:8080

**Comment by itsN1X** [comment]
Or you could skip the CLI gimmicks using VNC or FileZilla or something easier to get up your testing server running.. I run my own web servers in my apartment xD
